Initial version release v1.0.0

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -4,18 +4,6 @@ author: "FigMayo"
 branding:
   icon: "zap"
   color: "blue"
-keywords:
-  - figmayo
-  - figma
-  - design-tokens
-  - variables
-  - github-action
-  - design-system
-  - token-sync
-  - automation
-  - figma-integration
-  - pull-request
-  - design-ops
 inputs:
   gh-pat:
     description: "GitHub personal access token for authenticating gh CLI."
@@ -33,6 +21,24 @@ outputs:
 runs:
   using: "composite"
   steps:
+    - name: Validate Inputs
+      shell: bash
+      run: |
+        set -e
+        if [[ -z "${{ inputs.gh-pat }}" ]]; then
+          echo "❌ Error: 'gh-pat' input is required but not provided. Go here to create one https://github.com/settings/personal-access-tokens"
+          exit 1
+        fi
+
+        if [[ -z "${{ inputs.figmayo-api-key }}" ]]; then
+          echo "❌ Error: 'figmayo-api-key' input is required but not provided. Go here to create one https://app.figmayo.com/api/v2/settings"
+          exit 1
+        fi
+
+        if [[ -z "${{ inputs.file-path }}" ]]; then
+          echo "❌ Error: 'file-path' input is required but not provided."
+          exit 1
+        fi
     - name: Checkout Base Branch
       uses: actions/checkout@v4
 
